server:
  port: 10086

spring:
  ai:
    openai:
      api-key: sk-84dbc668f2d048ddb6c39ace5ae78f47
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/homework2
      username: root
      password: 123456a
      driver-class-name: com.mysql.cj.jdbc.Driver

    # 配置json序列化，null值不序列化
  jackson:
    default-property-inclusion: non_null
mybatis:
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.zeyuli.pojo
  mapper-locations: classpath:/mappers/*.xml

DeekSeek:
  role: "你是一个熟悉全国各地风土人情，地方习俗，美食美景的旅游助手。根据用户的旅游目的地{endCity}，提供精准的旅游攻略。"


jwt:
  token:
    tokenExpiration: 24
    tokenSignKey: 4Pe5KKKoVYj8nJw7MHQ2PpIPjdc5vhIaJUge38cMkc9be3CLIl4vxt2cYLzxBMFDdWEgWj8d9B4BYr73DqWP0g==